# Generated by Django 4.2.1 on 2024-04-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(editable=False)),
                ("text", models.TextField(verbose_name="Текст вопроса")),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время получения"
                    ),
                ),
                ("text_question", models.TextField(verbose_name="Текст вопроса")),
                ("user_name", models.TextField(verbose_name="Отправитель")),
            ],
        ),
    ]
