# Generated by Django 4.2.1 on 2024-04-04 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="text_question",
        ),
    ]
