# Generated by Django 4.2.1 on 2024-04-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_message__type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="_type",
            field=models.TextField(default="uuid", verbose_name="Тип сообщения"),
        ),
    ]
