# Generated by Django 4.2.1 on 2024-04-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0004_alter_message__type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="_type",
        ),
        migrations.AddField(
            model_name="message",
            name="chat_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(verbose_name="Текст сообщения"),
        ),
    ]
