# Generated by Django 4.0 on 2024-03-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Текст ответа')),
                ('question', models.TextField(verbose_name='Текст вопроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время получения')),
                ('is_liked', models.BooleanField(default=True, verbose_name='Понравился ли ответ')),
            ],
            options={
                'verbose_name': 'Сообщение от бота',
                'verbose_name_plural': 'Сообщения от бота',
            },
        ),
    ]
